
// This file has been generated by the GUI designer. Do not modify.
namespace org.maniacSoft.form.login
{
	public partial class LoginWnd
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget org.maniacSoft.form.login.LoginWnd
			this.Name = "org.maniacSoft.form.login.LoginWnd";
			this.Title = global::Mono.Unix.Catalog.GetString ("LoginWnd");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
