
// This file has been generated by the GUI designer. Do not modify.
namespace prjAsistencias
{
	public partial class CalendarDateSelectWnd
	{
		private global::Gtk.Fixed fixed1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget prjAsistencias.CalendarDateSelectWnd
			this.Name = "prjAsistencias.CalendarDateSelectWnd";
			this.Title = global::Mono.Unix.Catalog.GetString ("CalendarDateSelectWnd");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child prjAsistencias.CalendarDateSelectWnd.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
