
// This file has been generated by the GUI designer. Do not modify.
namespace prjAsistencias
{
	public partial class IngresoHorario
	{
		private global::Gtk.Fixed fixed5;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Table pnlHorario;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Entry txtIngreso;
		private global::Gtk.Entry txtSalida;
		private global::Gtk.Label fieldSetLabel;
		private global::Gtk.Button btnGuardar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget prjAsistencias.IngresoHorario
			this.Name = "prjAsistencias.IngresoHorario";
			this.Title = global::Mono.Unix.Catalog.GetString ("Registro de horas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child prjAsistencias.IngresoHorario.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame2.LabelYalign = 0.36F;
			this.frame2.BorderWidth = ((uint)(5));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.pnlHorario = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.pnlHorario.Name = "pnlHorario";
			this.pnlHorario.RowSpacing = ((uint)(10));
			this.pnlHorario.ColumnSpacing = ((uint)(15));
			this.pnlHorario.BorderWidth = ((uint)(11));
			// Container child pnlHorario.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ingreso</b>");
			this.label2.UseMarkup = true;
			this.pnlHorario.Add (this.label2);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.pnlHorario [this.label2]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHorario.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Salida</b>");
			this.label3.UseMarkup = true;
			this.pnlHorario.Add (this.label3);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.pnlHorario [this.label3]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHorario.Gtk.Table+TableChild
			this.txtIngreso = new global::Gtk.Entry ();
			this.txtIngreso.TooltipMarkup = "Hora de ingreso";
			this.txtIngreso.CanFocus = true;
			this.txtIngreso.Name = "txtIngreso";
			this.txtIngreso.IsEditable = true;
			this.txtIngreso.MaxLength = 5;
			this.txtIngreso.InvisibleChar = '•';
			this.pnlHorario.Add (this.txtIngreso);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.pnlHorario [this.txtIngreso]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pnlHorario.Gtk.Table+TableChild
			this.txtSalida = new global::Gtk.Entry ();
			this.txtSalida.CanFocus = true;
			this.txtSalida.Name = "txtSalida";
			this.txtSalida.IsEditable = true;
			this.txtSalida.MaxLength = 5;
			this.txtSalida.InvisibleChar = '•';
			this.pnlHorario.Add (this.txtSalida);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.pnlHorario [this.txtSalida]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.pnlHorario);
			this.frame2.Add (this.GtkAlignment);
			this.fieldSetLabel = new global::Gtk.Label ();
			this.fieldSetLabel.Name = "fieldSetLabel";
			this.fieldSetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Horario trabajo</b>");
			this.fieldSetLabel.UseMarkup = true;
			this.frame2.LabelWidget = this.fieldSetLabel;
			this.fixed5.Add (this.frame2);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.frame2]));
			w7.X = 60;
			w7.Y = 37;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnGuardar = new global::Gtk.Button ();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
			this.fixed5.Add (this.btnGuardar);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.btnGuardar]));
			w8.X = 172;
			w8.Y = 225;
			this.Add (this.fixed5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 424;
			this.DefaultHeight = 305;
			this.Show ();
			this.btnGuardar.Clicked += new global::System.EventHandler (this.OnBtnGuardarClicked);
		}
	}
}
